"""
report_gen.py — Bug Bounty Report Generator
Auto-generates professional Hackerone/Bugcrowd-ready reports for confirmed findings.
"""
import time
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

from plugins import register
from plugins.base import BaseTool, ToolResult


SEVERITY_MAP = {
    "critical": {"label": "Critical", "cvss_range": "9.0-10.0", "bounty_est": "$2,000-$20,000+"},
    "high":     {"label": "High",     "cvss_range": "7.0-8.9",  "bounty_est": "$500-$5,000"},
    "medium":   {"label": "Medium",   "cvss_range": "4.0-6.9",  "bounty_est": "$100-$1,000"},
    "low":      {"label": "Low",      "cvss_range": "0.1-3.9",  "bounty_est": "$50-$200"},
    "p1":       {"label": "Critical", "cvss_range": "9.0-10.0", "bounty_est": "$2,000-$20,000+"},
    "p2":       {"label": "High",     "cvss_range": "7.0-8.9",  "bounty_est": "$500-$5,000"},
    "p3":       {"label": "Medium",   "cvss_range": "4.0-6.9",  "bounty_est": "$100-$1,000"},
    "p4":       {"label": "Low",      "cvss_range": "0.1-3.9",  "bounty_est": "$50-$200"},
}

REPORT_TEMPLATE = """# [{severity_label}] {title}

**Severity**: {severity_label} (CVSS {cvss_range} | Est. bounty: {bounty_est})
**Target**: `{target}`
**Endpoint**: `{endpoint}`
**Date**: {date}

---

## Summary

{summary}

## Impact

{impact}

## Steps to Reproduce

{steps}

## Proof of Concept

```
{poc}
```

## Recommended Fix

{fix}

---
*Generated by MERGEN*
"""

IMPACTS = {
    "idor":          ("An attacker can access, modify, or delete data belonging to other users.",
                      "Implement server-side ownership checks on every resource access."),
    "sqli":          ("An attacker can extract the entire database, bypass authentication, or execute OS commands.",
                      "Use parameterized queries. Never concatenate user input into SQL strings."),
    "xss":           ("An attacker can steal session cookies or perform actions on behalf of victims.",
                      "Encode all user-supplied output. Implement a strict Content-Security-Policy."),
    "lfi":           ("An attacker can read arbitrary server files including credentials and source code.",
                      "Whitelist allowed paths. Never pass user input to file operations."),
    "rce":           ("An attacker can execute arbitrary commands on the server.",
                      "Remove dangerous functions. Implement strict input validation and sandboxing."),
    "ssrf":          ("An attacker can reach internal services and cloud metadata endpoints.",
                      "Whitelist allowed URL destinations. Block requests to private IP ranges."),
    "auth_bypass":   ("An attacker can access protected resources without authentication.",
                      "Enforce authentication at middleware level on all sensitive endpoints."),
    "upload_bypass": ("An attacker can upload malicious files such as PHP webshells.",
                      "Validate file type using magic bytes. Store uploads outside the web root."),
}


@register
class ReportGenPlugin(BaseTool):
    name        = "report_gen"
    description = "Generate a professional bug bounty report (Hackerone/Bugcrowd format) for a confirmed finding."
    category    = "misc"
    requires    = []

    async def run(self, target: str, options: Dict[str, Any]) -> ToolResult:
        vuln_type = options.get("vuln_type", "vulnerability").lower()
        severity  = options.get("severity", "medium").lower()
        endpoint  = options.get("endpoint", target)
        poc       = options.get("poc", "See steps above")
        steps_raw = options.get("steps", [])
        title     = options.get("title", f"{vuln_type.upper()} in {endpoint}")
        summary   = options.get("summary", "")

        sev_info = SEVERITY_MAP.get(severity, SEVERITY_MAP["medium"])
        impact, fix = self._get_impact_fix(vuln_type)

        if isinstance(steps_raw, list):
            steps_str = "\n".join(f"{i+1}. {s}" for i, s in enumerate(steps_raw))
        else:
            steps_str = str(steps_raw)

        if not steps_str:
            steps_str = self._default_steps(vuln_type, endpoint, poc)

        if not summary:
            summary = f"A {vuln_type} vulnerability was found at `{endpoint}`."

        report = REPORT_TEMPLATE.format(
            severity_label=sev_info["label"],
            title=title,
            cvss_range=sev_info["cvss_range"],
            bounty_est=sev_info["bounty_est"],
            target=target,
            endpoint=endpoint,
            date=datetime.utcnow().strftime("%Y-%m-%d"),
            summary=summary,
            impact=impact,
            steps=steps_str,
            poc=poc,
            fix=fix,
        )

        report_dir = Path("/tmp/mergen_reports")
        report_dir.mkdir(exist_ok=True)
        slug     = vuln_type.replace(" ", "_")
        filename = f"report_{slug}_{int(time.time())}.md"
        filepath = report_dir / filename

        file_error: str = ""
        try:
            filepath.write_text(report)
        except OSError as e:
            file_error = str(e)

        return ToolResult(
            tool=self.name,
            target=target,
            success=not bool(file_error),
            raw_output=report,
            findings=[{
                "type":     "report",
                "severity": severity,
                "title":    title,
                "file":     str(filepath) if not file_error else None,
                "preview":  report[:500],
                "error":    file_error or None,
            }],
            suggested_next=[],
            risk_score=0.0,
            metadata={"report_file": str(filepath), "severity": severity, "write_error": file_error},
        )

    def _get_impact_fix(self, vuln_type: str):
        for key, (impact, fix) in IMPACTS.items():
            if key in vuln_type:
                return impact, fix
        return (f"An attacker can exploit {vuln_type}.",
                "Implement proper input validation and security controls.")

    def _default_steps(self, vuln_type: str, endpoint: str, poc: str) -> str:
        if "idor" in vuln_type:
            return f"1. Log in as a regular user\n2. Send GET {endpoint}\n3. Change the ID to another user's\n4. Observe data returned"
        if "sqli" in vuln_type:
            return f"1. Navigate to {endpoint}\n2. Inject: ' OR '1'='1'--\n3. Observe SQL error or different response"
        if "xss" in vuln_type:
            return f"1. Navigate to {endpoint}\n2. Inject: <script>alert(document.cookie)</script>\n3. Observe execution"
        return f"1. Navigate to {endpoint}\n2. {poc}\n3. Observe vulnerability"
