# server/playbooks.py
"""
41 Kill Chain tanımları.
Her playbook: id, kategori, araçlar, koşullar, temel öncelik skoru.
PlaybookSelector bu tanımları kullanarak hangi playbook'ların
çalışacağını ve hangi sırayla çalışacağını belirler.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class PlaybookDef:
    id: str
    name: str
    category: str                    # "web", "api", "infra", "cloud"
    description: str
    tools: List[str]
    requires: List[str]              # surface_map'te olması gereken koşullar
    base_score: int                  # 0-100
    mode_weight: Dict[str, float]    # {"bb": 1.2, "pentest": 0.8, "ctf": 1.0}
    tech_keywords: List[str]
    tags: List[str] = field(default_factory=list)


WEB_PLAYBOOKS: List[PlaybookDef] = [
    PlaybookDef(id="oauth_oidc", name="OAuth 2.0 / OIDC Attack Chain", category="web",
        description="State bypass, redirect_uri manipulation, PKCE downgrade, code reuse",
        tools=["ffuf", "burp_passive", "jwt_tool"], requires=["has_web"], base_score=55,
        mode_weight={"bb": 1.3, "pentest": 1.0, "ctf": 0.8},
        tech_keywords=["oauth", "openid", "oidc", "auth0", "okta", "keycloak"], tags=["auth", "web"]),
    PlaybookDef(id="jwt_attack_chain", name="JWT Attack Chain", category="web",
        description="alg:none, RS→HS confusion, weak secret brute, kid traversal, jwks spoof",
        tools=["jwt_tool", "hashcat"], requires=["has_web"], base_score=60,
        mode_weight={"bb": 1.4, "pentest": 1.2, "ctf": 1.5},
        tech_keywords=["jwt", "json web token", "bearer", "authorization: bearer"], tags=["auth", "web", "api"]),
    PlaybookDef(id="graphql_full_chain", name="GraphQL Full Chain", category="web",
        description="Introspection dump, batch DoS, alias IDOR, mutation auth bypass",
        tools=["graphw00f", "ffuf", "nuclei"], requires=["has_web"], base_score=65,
        mode_weight={"bb": 1.5, "pentest": 1.2, "ctf": 1.0},
        tech_keywords=["graphql", "graph api", "/graphql", "/api/graphql"], tags=["api", "web"]),
    PlaybookDef(id="ssrf_full_chain", name="SSRF Full Chain", category="web",
        description="Cloud metadata, DNS rebinding, blind SSRF OOB, IPv6 bypass",
        tools=["ffuf", "nuclei", "ssrfmap"], requires=["has_web"], base_score=70,
        mode_weight={"bb": 1.6, "pentest": 1.4, "ctf": 1.2},
        tech_keywords=["url", "fetch", "redirect", "proxy", "webhook", "callback"], tags=["web", "cloud"]),
    PlaybookDef(id="idor_bola", name="IDOR / BOLA Hunt", category="web",
        description="Sequential ID enum, UUID predict, mass assignment, priv-esc",
        tools=["ffuf", "arjun", "nuclei"], requires=["has_web"], base_score=65,
        mode_weight={"bb": 1.5, "pentest": 1.3, "ctf": 1.2},
        tech_keywords=["id=", "user_id", "account_id", "object_id", "uuid"], tags=["web", "api"]),
    PlaybookDef(id="file_upload_rce", name="File Upload → RCE", category="web",
        description="Extension bypass, magic bytes spoof, polyglot, zip slip, SVG XXE",
        tools=["ffuf", "nuclei"], requires=["has_web"], base_score=60,
        mode_weight={"bb": 1.4, "pentest": 1.5, "ctf": 1.8},
        tech_keywords=["upload", "file", "attachment", "import", "multipart"], tags=["web", "rce"]),
    PlaybookDef(id="xss_ato", name="XSS → Account Takeover", category="web",
        description="Reflected/stored/DOM, CSP bypass, cookie steal, postMessage abuse",
        tools=["dalfox", "nuclei"], requires=["has_web"], base_score=55,
        mode_weight={"bb": 1.3, "pentest": 1.0, "ctf": 1.2},
        tech_keywords=["search", "query", "input", "comment", "message"], tags=["web"]),
    PlaybookDef(id="template_injection", name="Template Injection (SSTI)", category="web",
        description="Jinja2, Twig, Freemarker, Velocity, EL injection",
        tools=["tplmap", "ffuf"], requires=["has_web"], base_score=55,
        mode_weight={"bb": 1.2, "pentest": 1.3, "ctf": 1.5},
        tech_keywords=["jinja", "twig", "freemarker", "thymeleaf", "template", "render"], tags=["web", "rce"]),
    PlaybookDef(id="deserialization", name="Deserialization Attack", category="web",
        description="Java gadget chains, PHP object injection, Python pickle",
        tools=["ysoserial", "nuclei"], requires=["has_web"], base_score=50,
        mode_weight={"bb": 1.1, "pentest": 1.3, "ctf": 1.6},
        tech_keywords=["java", "php", "python", "pickle", "serialize", "deserialization"], tags=["web", "rce"]),
    PlaybookDef(id="xxe_full_chain", name="XXE Full Chain", category="web",
        description="Classic, blind OOB, SVG/XLSX/DOCX XXE, XXE→SSRF pivot",
        tools=["xxeinjector", "nuclei", "ffuf"], requires=["has_web"], base_score=55,
        mode_weight={"bb": 1.2, "pentest": 1.3, "ctf": 1.4},
        tech_keywords=["xml", "soap", "wsdl", "docx", "xlsx", "svg", "import"], tags=["web"]),
    PlaybookDef(id="business_logic", name="Business Logic Abuse", category="web",
        description="Race conditions, negative price, coupon stacking, workflow skip",
        tools=["ffuf", "nuclei"], requires=["has_web"], base_score=50,
        mode_weight={"bb": 1.4, "pentest": 1.0, "ctf": 0.8},
        tech_keywords=["price", "payment", "order", "cart", "checkout", "coupon", "discount"], tags=["web", "logic"]),
    PlaybookDef(id="http_smuggling", name="HTTP Request Smuggling", category="web",
        description="CL.TE, TE.CL, TE.TE, H2 desync, prefix poisoning",
        tools=["smuggler", "nuclei"], requires=["has_web"], base_score=45,
        mode_weight={"bb": 1.2, "pentest": 1.1, "ctf": 1.0},
        tech_keywords=["http/1.1", "transfer-encoding", "content-length", "proxy", "cdn"], tags=["web", "infra"]),
]

API_PLAYBOOKS: List[PlaybookDef] = [
    PlaybookDef(id="rest_api_owasp", name="REST API OWASP Top 10", category="api",
        description="Broken object auth, mass assignment, unrestricted consumption",
        tools=["ffuf", "nuclei", "arjun"], requires=["has_web"], base_score=70,
        mode_weight={"bb": 1.5, "pentest": 1.3, "ctf": 1.0},
        tech_keywords=["api", "/api/", "rest", "json", "application/json"], tags=["api"]),
    PlaybookDef(id="graphql_deep", name="GraphQL Deep Dive", category="api",
        description="Schema dump, subscription abuse, resolver timing, nested DoS",
        tools=["graphqlmap", "ffuf"], requires=["has_web"], base_score=65,
        mode_weight={"bb": 1.5, "pentest": 1.2, "ctf": 1.0},
        tech_keywords=["graphql", "apollo", "hasura", "strapi"], tags=["api"]),
    PlaybookDef(id="grpc_protobuf", name="gRPC / Protobuf Attack", category="api",
        description="Reflection service enum, untyped field injection, metadata injection",
        tools=["grpcurl", "grpcui"], requires=["has_web"], base_score=45,
        mode_weight={"bb": 1.0, "pentest": 1.3, "ctf": 0.8},
        tech_keywords=["grpc", "protobuf", "proto", "h2c"], tags=["api"]),
    PlaybookDef(id="api_key_leakage", name="API Key Leakage Chain", category="api",
        description="GitHub code search, JS file regex, .env exposure, Shodan dork",
        tools=["trufflehog", "gau", "ffuf"], requires=["has_web"], base_score=75,
        mode_weight={"bb": 1.6, "pentest": 1.4, "ctf": 0.8},
        tech_keywords=["api_key", "api-key", "secret", "token", "password"], tags=["api", "secrets"]),
    PlaybookDef(id="websocket_security", name="WebSocket Security", category="api",
        description="Origin bypass, message injection, auth downgrade, CSWSH",
        tools=["nuclei", "ffuf"], requires=["has_web"], base_score=50,
        mode_weight={"bb": 1.2, "pentest": 1.1, "ctf": 1.2},
        tech_keywords=["websocket", "ws://", "wss://", "upgrade: websocket"], tags=["api", "web"]),
    PlaybookDef(id="api_versioning_abuse", name="API Versioning Abuse", category="api",
        description="v1 vs v2 auth diff, deprecated endpoint bypass, version header",
        tools=["ffuf", "arjun"], requires=["has_web"], base_score=55,
        mode_weight={"bb": 1.3, "pentest": 1.1, "ctf": 0.9},
        tech_keywords=["/v1/", "/v2/", "/api/v", "api-version", "version"], tags=["api"]),
    PlaybookDef(id="rate_limit_bypass", name="Rate Limiting Bypass", category="api",
        description="IP rotation, X-Forwarded-For spoof, timing enum, no lockout",
        tools=["ffuf", "nuclei"], requires=["has_web"], base_score=50,
        mode_weight={"bb": 1.2, "pentest": 1.0, "ctf": 0.8},
        tech_keywords=["login", "auth", "password", "reset", "otp", "verify"], tags=["api", "auth"]),
    PlaybookDef(id="swagger_openapi_recon", name="Swagger / OpenAPI Recon", category="api",
        description="Exposed docs, undocumented fields, example value injection",
        tools=["ffuf", "nuclei", "katana"], requires=["has_web"], base_score=65,
        mode_weight={"bb": 1.4, "pentest": 1.2, "ctf": 0.9},
        tech_keywords=["swagger", "openapi", "/docs", "/api-docs", "redoc", "/swagger"], tags=["api", "recon"]),
    PlaybookDef(id="mobile_api_reverse", name="Mobile API Reverse", category="api",
        description="APK decompile, endpoint extraction, SSL pinning bypass, token replay",
        tools=["apktool", "nuclei"], requires=["has_web"], base_score=35,
        mode_weight={"bb": 1.1, "pentest": 0.9, "ctf": 0.7},
        tech_keywords=["android", "apk", "mobile", "app"], tags=["api", "mobile"]),
]

INFRA_PLAYBOOKS: List[PlaybookDef] = [
    PlaybookDef(id="active_directory_chain", name="Active Directory Full Chain", category="infra",
        description="BloodHound → Kerberoast → AS-REP → PTH → DCSync → Golden Ticket",
        tools=["enum4linux", "netexec", "nmap"], requires=["has_smb"], base_score=75,
        mode_weight={"bb": 0.8, "pentest": 1.8, "ctf": 1.5},
        tech_keywords=["active directory", "ldap", "kerberos", "domain", "dc="], tags=["infra", "windows", "ad"]),
    PlaybookDef(id="smb_netbios", name="SMB / NetBIOS Hunt", category="infra",
        description="Null session, signing check, relay, EternalBlue/PrintNightmare",
        tools=["enum4linux", "smbmap", "netexec", "nmap"], requires=["has_smb"], base_score=70,
        mode_weight={"bb": 0.7, "pentest": 1.7, "ctf": 1.5},
        tech_keywords=["smb", "cifs", "netbios", "samba"], tags=["infra", "windows"]),
    PlaybookDef(id="ldap_recon", name="LDAP Recon → Abuse", category="infra",
        description="Anonymous bind, user enum, password spray, ACL abuse",
        tools=["nmap", "netexec"], requires=["has_smb"], base_score=60,
        mode_weight={"bb": 0.6, "pentest": 1.6, "ctf": 1.3},
        tech_keywords=["ldap", "389", "636", "active directory", "openldap"], tags=["infra", "windows"]),
    PlaybookDef(id="mssql_mysql_abuse", name="MSSQL / MySQL Abuse", category="infra",
        description="Default creds, xp_cmdshell, UDF injection, linked server pivot",
        tools=["sqlmap", "nmap", "netexec"], requires=["has_db"], base_score=65,
        mode_weight={"bb": 1.0, "pentest": 1.5, "ctf": 1.4},
        tech_keywords=["mssql", "mysql", "sql server", "mariadb", "1433", "3306"], tags=["infra", "db"]),
    PlaybookDef(id="network_service_exploit", name="Network Service Exploit", category="infra",
        description="nmap → searchsploit → Metasploit module match → PoC",
        tools=["nmap", "searchsploit"], requires=["open_ports"], base_score=55,
        mode_weight={"bb": 0.8, "pentest": 1.4, "ctf": 1.6},
        tech_keywords=["version", "service", "exploit", "cve"], tags=["infra"]),
    PlaybookDef(id="vpn_rdp_exposure", name="VPN / RDP Exposure", category="infra",
        description="BlueKeep detect, NLA bypass, credential stuffing, MFA fatigue",
        tools=["nmap", "hydra"], requires=["has_rdp"], base_score=60,
        mode_weight={"bb": 0.9, "pentest": 1.5, "ctf": 1.2},
        tech_keywords=["rdp", "3389", "vpn", "citrix", "globalprotect", "pulse"], tags=["infra"]),
    PlaybookDef(id="container_k8s_escape", name="Container / K8s Escape", category="infra",
        description="Exposed dashboard, RBAC wildcard, privileged pod, etcd no-auth",
        tools=["nmap", "nuclei"], requires=["has_web"], base_score=55,
        mode_weight={"bb": 1.1, "pentest": 1.4, "ctf": 1.3},
        tech_keywords=["kubernetes", "k8s", "docker", "container", "etcd", "kubectl"], tags=["infra", "cloud"]),
    PlaybookDef(id="firewall_ids_evasion", name="Firewall / IDS Evasion", category="infra",
        description="Fragmentation, TTL manipulation, decoy scan, timing evasion",
        tools=["nmap"], requires=["waf_detected"], base_score=40,
        mode_weight={"bb": 0.7, "pentest": 1.3, "ctf": 1.0},
        tech_keywords=["firewall", "waf", "ids", "ips", "cloudflare", "akamai"], tags=["infra", "evasion"]),
    PlaybookDef(id="snmp_ipmi_oob", name="SNMP / IPMI / OOB", category="infra",
        description="SNMPv1/v2 community string, IPMI 2.0 RAKP hash dump",
        tools=["nmap"], requires=["open_ports"], base_score=40,
        mode_weight={"bb": 0.5, "pentest": 1.2, "ctf": 0.8},
        tech_keywords=["snmp", "ipmi", "161", "623", "bmc", "idrac", "ilo"], tags=["infra"]),
    PlaybookDef(id="email_mail_server", name="Email / Mail Server", category="infra",
        description="Open relay, SPF/DMARC/DKIM enum, O365/Exchange fingerprint",
        tools=["nmap", "whatweb"], requires=["open_ports"], base_score=35,
        mode_weight={"bb": 1.0, "pentest": 1.1, "ctf": 0.6},
        tech_keywords=["smtp", "imap", "pop3", "exchange", "o365", "25", "587", "993"], tags=["infra", "email"]),
]

CLOUD_PLAYBOOKS: List[PlaybookDef] = [
    PlaybookDef(id="aws_full_chain", name="AWS Full Attack Chain", category="cloud",
        description="S3 misconfig → IMDSv1 SSRF → IAM key → admin escalation",
        tools=["nuclei", "ffuf", "trufflehog"], requires=["has_web"], base_score=75,
        mode_weight={"bb": 1.6, "pentest": 1.5, "ctf": 1.0},
        tech_keywords=["aws", "amazon", "s3", "ec2", "lambda", "cloudfront", ".amazonaws.com"], tags=["cloud", "aws"]),
    PlaybookDef(id="azure_attack_chain", name="Azure Attack Chain", category="cloud",
        description="Blob anon → SAS leak → AAD enum → PRT theft → tenant takeover",
        tools=["nuclei", "trufflehog", "ffuf"], requires=["has_web"], base_score=70,
        mode_weight={"bb": 1.5, "pentest": 1.4, "ctf": 0.9},
        tech_keywords=["azure", "microsoft", "blob", "azurewebsites.net", "sharepoint", "teams"], tags=["cloud", "azure"]),
    PlaybookDef(id="gcp_attack_chain", name="GCP Attack Chain", category="cloud",
        description="Storage ACL → workload identity → service account key → IAM escalation",
        tools=["nuclei", "trufflehog"], requires=["has_web"], base_score=65,
        mode_weight={"bb": 1.4, "pentest": 1.3, "ctf": 0.8},
        tech_keywords=["gcp", "google cloud", "appspot.com", "googleapis.com", "firebase"], tags=["cloud", "gcp"]),
    PlaybookDef(id="multi_cloud_secret_hunt", name="Multi-Cloud Secret Hunt", category="cloud",
        description=".env, terraform.tfstate, CI/CD vars, Dockerfile ARG leak",
        tools=["trufflehog", "gau", "ffuf", "nuclei"], requires=["has_web"], base_score=80,
        mode_weight={"bb": 1.7, "pentest": 1.5, "ctf": 1.0},
        tech_keywords=["env", "secret", "key", "token", "credential", ".env", "terraform"], tags=["cloud", "secrets"]),
    PlaybookDef(id="serverless_lambda", name="Serverless / Lambda Attack", category="cloud",
        description="Env var dump via SSRF, event injection, role overpermission",
        tools=["ffuf", "nuclei"], requires=["has_web"], base_score=60,
        mode_weight={"bb": 1.3, "pentest": 1.2, "ctf": 0.9},
        tech_keywords=["lambda", "serverless", "function", "faas", "vercel", "netlify"], tags=["cloud"]),
    PlaybookDef(id="cdn_cache_poisoning", name="CDN / Cache Poisoning", category="cloud",
        description="Cache key normalization, unkeyed header injection, web cache deception",
        tools=["ffuf", "nuclei"], requires=["has_web"], base_score=55,
        mode_weight={"bb": 1.3, "pentest": 1.1, "ctf": 1.0},
        tech_keywords=["cdn", "cache", "cloudflare", "fastly", "varnish", "x-cache"], tags=["cloud", "web"]),
    PlaybookDef(id="container_registry_abuse", name="Container Registry Abuse", category="cloud",
        description="ECR/GCR anon pull, image layer secret scan, Dockerfile leak",
        tools=["trufflehog", "nuclei"], requires=["has_web"], base_score=50,
        mode_weight={"bb": 1.1, "pentest": 1.2, "ctf": 0.8},
        tech_keywords=["docker", "registry", "ecr", "gcr", "ghcr.io", "dockerhub"], tags=["cloud", "container"]),
    PlaybookDef(id="cicd_pipeline_attack", name="CI/CD Pipeline Attack", category="cloud",
        description="GitHub Actions secret exfil, OIDC abuse, dependency confusion",
        tools=["trufflehog", "gau"], requires=["has_web"], base_score=65,
        mode_weight={"bb": 1.4, "pentest": 1.3, "ctf": 0.7},
        tech_keywords=["github actions", "jenkins", "gitlab ci", "circleci", "travis", ".yml"], tags=["cloud", "cicd"]),
    PlaybookDef(id="cloud_misconfiguration", name="Cloud Misconfiguration Sweep", category="cloud",
        description="S3 anon read/write, exposed dashboards, logging disabled",
        tools=["nuclei", "ffuf"], requires=["has_web"], base_score=70,
        mode_weight={"bb": 1.5, "pentest": 1.4, "ctf": 0.8},
        tech_keywords=["s3", "storage", "bucket", "blob", "public", "acl"], tags=["cloud"]),
    PlaybookDef(id="cloud_metadata_imds", name="Cloud Metadata / IMDS", category="cloud",
        description="IMDSv1 no-hop-limit, GCP/Azure metadata, SSRF chain",
        tools=["nuclei", "ffuf"], requires=["has_web"], base_score=70,
        mode_weight={"bb": 1.5, "pentest": 1.4, "ctf": 1.1},
        tech_keywords=["metadata", "169.254.169.254", "imds", "instance", "cloud"], tags=["cloud", "ssrf"]),
]

ALL_PLAYBOOKS: List[PlaybookDef] = WEB_PLAYBOOKS + API_PLAYBOOKS + INFRA_PLAYBOOKS + CLOUD_PLAYBOOKS
PLAYBOOK_MAP: Dict[str, PlaybookDef] = {p.id: p for p in ALL_PLAYBOOKS}


def get_playbook(playbook_id: str) -> Optional[PlaybookDef]:
    return PLAYBOOK_MAP.get(playbook_id)


def get_by_category(category: str) -> List[PlaybookDef]:
    return [p for p in ALL_PLAYBOOKS if p.category == category]
